# Generated by Django 5.1.4 on 2025-02-10 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aiutorapp', '0004_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='course_files/'),
        ),
    ]
