# Generated by Django 5.1.4 on 2025-02-12 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aiutorapp', '0005_course_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='media_files',
            field=models.FileField(blank=True, null=True, upload_to='media_files/'),
        ),
        migrations.AddField(
            model_name='course',
            name='youtube_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
